version: "3.8"
services:
  backend:
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false
      - spring.datasource.username=$MYSQLDB_USER
      - spring.datasource.password=$MYSQLDB_ROOT_PASSWORD
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
    volumes:
      - "${HOME}/.m2:/root/.m2"
    networks:
      - springmysql-network
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    env_file: ./.env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
    networks:
      - springmysql-network
    volumes:
      - alphadb:/var/lib/mysql

networks:
  springmysql-network:
  
volumes:
  alphadb:

