version: "3"
services:
  server:
    image: backend
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/alphadb?useSSL=false
    networks:
      - springmysql-network
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - springmysql-network
    volumes:
      - alphadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=alphadb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234

networks:
  springmysql-network:
  
volumes:
  alphadb:

